### ISSUE TITLE
Package.json types definition not working properly

### ISSUE THREAD

**Issue by RazorSiM** [launchdarkly/vue-client-sdk#23]
**Describe the bug**
Typescript does not infer types from the package, throwing a `TS7016` error:

```
Could not find a declaration file for module 'launchdarkly-vue-client-sdk'. '/project/node_modules/.pnpm/launchdarkly-vue-client-sdk@2.0.1_vue@3.3.4/node_modules/launchdarkly-vue-client-sdk/dist/launchdarkly-vue-client-sdk.es.js' implicitly has an 'any' type.
  There are types at '/project/node_modules/launchdarkly-vue-client-sdk/dist/src/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'launchdarkly-vue-client-sdk' library may need to update its package.json or typings.
```

**To reproduce**
Create a Vue app and import the package.
Currently, I'm using node 18.16.0 and Typescript 5.0.4.

**Expected behavior**
The types should be imported correctly.

**SDK version**
`"launchdarkly-vue-client-sdk": "^2.0.1"`

**Language version, developer tools**
Vue, Typescript and Vite as a bundler.

**OS/platform**
Fedora 38, MacOS 13.4.1

**Additional context**
I monkey-patched the library by adding additional fields to the exports:
```json
  "exports": {
    "import": {
      "default": "./dist/launchdarkly-vue-client-sdk.es.js",
      "types": "./dist/src/index.d.ts"
    },
    "require": {
      "default": "./dist/launchdarkly-vue-client-sdk.umd.js",
      "types": "./dist/src/index.d.ts"
    }
  },
```
This way, everything works.

**Comment by yusinto** [comment]
This has been fixed in #24 .
