### ISSUE TITLE
LD with Astro

### ISSUE THREAD

**Issue by alex129** [launchdarkly/vue-client-sdk#32]
Hello! I'm trying to use Vue SDK with Astro, the problem is that when I use it in a basic component like that:

```
<script setup lang="ts">
  import { useLDFlag } from 'launchdarkly-vue-client-sdk'
  const featureFlagKey = 'my-boolean-flag'
  const myFlagValue = useLDFlag(featureFlagKey, false /* default flag value */)
</script>
<template>
  Feature flag "{{ featureFlagKey }}" has value "{{ myFlagValue }}".
</template>
```

It throw me an error:

![image](https://github.com/launchdarkly/vue-client-sdk/assets/10452211/e5ceb6a5-e6e2-4f83-b08a-371fb79cdeaf)

I could fix it changing the type: 'module' in the package json of the SDK but that's not the way.

Anyone can help me with that? Thanks

**Comment by yusinto** [comment]
Thanks for submitting this issue. We will investigate and provide an update soon. Internally logged as 226912.

**Comment by yusinto** [comment]
[2.0.5](https://github.com/launchdarkly/vue-client-sdk/releases/tag/2.0.5) was released which should fix this issue.
