### ISSUE TITLE
Documentation is invalid

### ISSUE THREAD

**Issue by illegalnumbers** [launchdarkly/vue-client-sdk#36]
https://docs.launchdarkly.com/sdk/client-side/vue#retrieving-flag-values-with-the-client This documentation is invalid.

Clearly, from this https://github.com/launchdarkly/vue-client-sdk/blob/main/src/hooks.ts#L28 call, you cannot use 
```
import { useLDClient } from 'launchdarkly-vue-client-sdk'
const ldClient = useLDClient() <-- will throw an exception
const allFlags = ldClient.allFlags()``` outside of a component.
```
 This is clearly wrong.

**Comment by yusinto** [comment]
Thank you for reporting this issue. We are looking into this and will provide an update soon. Internally logged as #235367.
